USE SALARIE
USE MASTER
-- Créer la base uniquement si inexistante
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'SALARIE')
BEGIN
	CREATE DATABASE SALARIE;
END

GO
USE SALARIE;
GO

-- Créer la table DEPARTEMENT si inexistante
IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE name = 'DEPARTEMENT')
BEGIN
	CREATE TABLE DEPARTEMENT
	(DPTNO TINYINT NOT NULL,
	DPTNOM NVARCHAR(50) NOT NULL,
	DPTLOC NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_DPTNO PRIMARY KEY (DPTNO)
	)
END


-- Créer la table EMPLOYE si inexistante
IF NOT EXISTS (SELECT * FROM sys.sysobjects WHERE name = 'EMPLOYE') 
BEGIN
	CREATE TABLE EMPLOYE
	(EMPNO SMALLINT NOT NULL,
	EMPNOM NVARCHAR(50) NOT NULL,
	EMPMETIER NVARCHAR(50) NOT NULL,
	EMPEMBDATE DATE NOT NULL,
	EMPSAL MONEY NOT NULL,
	EMPCOMM MONEY,
	MGRNO SMALLINT,
	DPTNO TINYINT NOT NULL,
	CONSTRAINT PK_EMPNO PRIMARY KEY (EMPNO),
	CONSTRAINT FK_EMP_DPTNO FOREIGN KEY (DPTNO) REFERENCES DEPARTEMENT (DPTNO),
	CONSTRAINT FK_MGR_EMPNO FOREIGN KEY (MGRNO) REFERENCES EMPLOYE (EMPNO)
	);
END

--EXEC sp_rename 'EMPLOYE.EMPJOB', 'EMPMETIER', 'COLUMN';

-- Ajout d'une contrainte check sur les job des EMPLOYEloyés. Cela force les entrées de job à avoir les valeurs spécifiées
IF NOT EXISTS (SELECT * from sys.sysobjects WHERE name = 'CK_EMPLOYE_JOB' AND xtype = 'C')  -- xtype = 'C' => le type des objets cherchés est le type contrainte de type check
BEGIN
	ALTER TABLE EMPLOYE
	ADD CONSTRAINT CK_EMPLOYE_JOB CHECK (JOB IN ('SALESMAN', 'PRESIDENT', 'MANAGER', 'ANALYST', 'CLERK'));
END

IF NOT EXISTS ( SELECT * FROM sys.sysobjects where name = 'PROJET' AND xtype = 'U')
BEGIN 
	CREATE TABLE PROJET(
	PROJNO INT IDENTITY(101,1),
	PROJNOM VARCHAR(5) NOT NULL,
	PROJBUDGET INT NOT NULL);
END

IF NOT EXISTS (SELECT * from sys.sysobjects WHERE name = 'PK_PROJET' AND xtype = 'PK')  -- xtype = 'PK' => le type des objets cherchés est le type contrainte de type clé primaire
BEGIN
	ALTER TABLE PROJET
	ADD CONSTRAINT PK_PROJET PRIMARY KEY (PROJNO);
END

-- Ajout de la colonne PROJNO dans la table EMPLOYE si elle n'existe pas déjà
IF NOT EXISTS (SELECT PROJNO FROM EMPLOYE)
BEGIN
	ALTER TABLE EMPLOYE
	ADD PROJNO INT;
END


SELECT * FROM EMPLOYE
SELECT * FROM PROJET
SELECT * FROM DEPARTEMENT